Artist.create( name:"Moodymann", country:"United States")
Artist.create( name:"Bernard Fornichelli", country:"Italy")
Artist.create( name:"De la Soul", country:"United States")
Artist.create( name:"Sven Väth", country:"Germany")
Artist.create( name:"Debonair", country:"France")
Artist.create( name:"The Rhythm Makers", country:"South-Africa")
Artist.create( name:"Cerrone", country:"France")
Artist.create( name:"Boz Scaggs", country:"United States")
Artist.create( name:"Billie", country:"United States")


Song.create(title:"Music People", album:"Silent Introduction", year:1998 ,cover:"http://res.cloudinary.com/codaisseur/image/upload/v1461268186/moodymann_blua3d.jpg", ylink:"https://www.youtube.com/watch?v=oCRAwBxu_l8")
Song.create(title:"Dirty Little Bonus Beats", album:"Black Mahogani", year:2004 ,cover:"http://res.cloudinary.com/codaisseur/image/upload/v1461269542/249_dmtivs.jpg", ylink:"https://www.youtube.com/watch?v=xthXy6ZtL7s")
Song.create(title:"Money Talks", album:"Money Talks EP", year:1978 ,cover:"http://res.cloudinary.com/codaisseur/image/upload/v1461268339/moneytalks_pmfbrr.jpg", ylink:"https://www.youtube.com/watch?v=maUQO2GkPVk")
Song.create(title:"Ring Ring Ring (Ha Ha Hey)", album:"Ring Ring EP", year:1991 ,cover:"http://res.cloudinary.com/codaisseur/image/upload/v1461268186/delasoul_imko1i.jpg", ylink:"https://www.youtube.com/watch?v=gC1xuVCBl4o")
Song.create(title:"Discophon", album:"Fusion", year:1999 ,cover:"http://res.cloudinary.com/codaisseur/image/upload/v1461268186/svenvath_rc1jfj.jpg", ylink:"https://www.youtube.com/watch?v=mdSsrD4ATzU")
Song.create(title:"Debonair", album:"Debon EP", year:2012 ,cover:"http://res.cloudinary.com/codaisseur/image/upload/v1461268186/debonair_ltykyi.jpg", ylink:"https://www.youtube.com/watch?v=4VlQJGaPkVc")
Song.create(title:"Soul on your Side", album:"Silent Introduction", year:1976 ,cover:"http://res.cloudinary.com/codaisseur/image/upload/v1461268187/sys_fbcfmk.jpg", ylink:"https://www.youtube.com/watch?v=spzO2_5HArQ")
Song.create(title:"Give me Love", album:"Supernature", year:1977 ,cover:"http://res.cloudinary.com/codaisseur/image/upload/v1461268187/cerrone_avtcqt.jpg", ylink:"https://www.youtube.com/watch?v=tee4asSKj8A")
Song.create(title:"Lowdown", album:"Silk Degrees", year:1976 ,cover:"http://res.cloudinary.com/codaisseur/image/upload/v1461268186/bozz_k1ynvf.jpg", ylink:"https://www.youtube.com/watch?v=I-hKBmTAADo")
Song.create(title:"Nobody's Business", album:"Chicago", year:1986 ,cover:"http://res.cloudinary.com/codaisseur/image/upload/v1461268186/billie_phjjwl.jpg", ylink:"https://www.youtube.com/watch?v=Wg_63AFViJQ")
